# Generated by Django 4.0.1 on 2022-01-17 16:22

from django.db import migrations, models
import django.utils.timezone
import tkinter.tix


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('slug', models.SlugField(blank=tkinter.tix.Tree, null=tkinter.tix.Tree, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
